### ISSUE TITLE
EC2 Instance timing out

### ISSUE THREAD

**Issue by jreneew2** [trevor-laher/OnDemandMinecraft#10]
Hey,

I successfully set this up and I can't get it to connect successfully. It says the instance is running, but it times out and if I do connect, everything is really slow. I am using t3-small

**Comment by ShironCat** [comment]
I've had the same issue. Turns out the ssh command sent by the heroku app to start the server sends a argument telling the minecraft server.jar to pre allocate 1G of memory. I've removed the argument to let it allocate as needed and it worked fine. But you might want to set this argument to meet your available ram space.

**Comment by jreneew2** [comment]
Yeah, that definitely seems to be the issue. I initially had the t3-micro which only has 1GB of ram so when I launched the sever, it started to swap and I was unable to access via ssh. I ended up deleted the instance and changed it to small and that seems to help. It just takes a bit to launch.

**Comment by trevor-laher** [comment]
I'm going to update the configuration file so that RAM size can be specified, but will be omitted by default.
